### ISSUE TITLE
JavaScriptの非同期処理を分かりやすく解説しているリンク集を載せる

### ISSUE THREAD

**Issue by keitakn** [keitakn/web-developer-ojt#38]
## 完了の定義
- 表題の記事を紹介している資料を作成する事

## 分かりやすい資料

- https://qiita.com/YoshikiNakamura/items/732ded26c85a7f771a27
- https://qiita.com/akameco/items/cc73afcdb5ac5d0774bc
- https://qiita.com/niusounds/items/37c1f9b021b62194e077
- https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by keita-nishimoto** [comment]
非同期処理に限らないが下記の記事も良さそう。

https://ics.media/entry/17262

**Comment by keitakn** [comment]
Promise と async/await の理解度をもう1段階上げる
https://qiita.com/SotaSuzuki/items/f23199e864cba47455ce

こちらも良質な記事
