### ISSUE TITLE
IT技術の学習方法に参考資料を追加する

### ISSUE THREAD

**Issue by keitakn** [keitakn/web-developer-ojt#46]
## 完了の定義
- 参考になりそうな記事があったので載せておく事

## 参考URL
- [勉強会聴講：「エンジニアとしてこの先生きのこるために」](https://qiita.com/sakaizay/items/e4ae74bfecd026925e3b)

**Comment by keita-nishimoto** [comment]
https://qiita.com/newta/items/f4aff8cdd8706d5d08c5

こちらの資料も参考になりそう。
