### ISSUE TITLE
PHPのところでマークダウン崩れが発生しているので修正する

### ISSUE THREAD

**Issue by keitakn** [keitakn/web-developer-ojt#48]
## 完了の定義
- 表題の件が実施されている事

**Comment by keita-nishimoto** [comment]
PHPのシェアが載っている新しい記事があったのでついでに載せておく。

https://news.mynavi.jp/article/20180109-567522/

**Comment by keita-nishimoto** [comment]
以下のページもマークダウンが崩れているので修正する。

https://github.com/keita-nishimoto/web-developer-ojt/tree/master/docs/http
